---
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/back"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "daily"