name: Deploy to Development

on:
  push:
    branches:
      - dev

jobs:
  test-backend:
    uses: ./.github/workflows/test-backend.yml # Appel du workflow test-backend.yml

  build-and-deploy:
    needs: test-backend # Assurez-vous que ce job s'exécute après test-backend
    runs-on: ubuntu-24.04

    env:
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      BACKEND_URL: ${{  vars.BACKEND_URL_DEV }}

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to Azure Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: 'Build and Push Docker Image Front'
        run: |
            docker build ./front --build-arg BACKEND_URL=${{  vars.BACKEND_URL_DEV }} -t ${{ secrets.ACR_LOGIN_SERVER }}/front:${{ github.sha }}
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/front:${{ github.sha }}

      - name: 'Build and Push Docker Image Back'
        run: |
          docker build ./back -t ${{ secrets.ACR_LOGIN_SERVER }}/back:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/back:${{ github.sha }}

      - name: 'Retrieve Information'
        run: |
            echo "Commit SHA: ${{ github.sha }}"
