name: Deploy to Production

on:
  push:
    tags:
      - "v*" 

jobs:
  test-backend:
    uses: ./.github/workflows/test-backend.yml # Appel du workflow test-backend.yml

  build-and-deploy:
    needs : test-backend
    runs-on: ubuntu-24.04

    env:
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      BACKEND_URL: ${{  vars.BACKEND_URL_PROD }}

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER_PROD }}
          username: ${{ secrets.ACR_USERNAME_PROD }}
          password: ${{ secrets.ACR_PASSWORD_PROD }}

      - name: Build and push Docker image for Prod
        run: |
          docker build ./back -t ${{ secrets.ACR_LOGIN_SERVER_PROD }}/back:${GITHUB_REF#refs/tags/}
          docker push ${{ secrets.ACR_LOGIN_SERVER_PROD }}/back:${GITHUB_REF#refs/tags/}
      
      - name: 'Build and Push Docker Image Front'
        run: |
            docker build ./front --build-arg BACKEND_URL=${{  vars.BACKEND_URL_PROD }} -t ${{ secrets.ACR_LOGIN_SERVER_PROD }}/front:${GITHUB_REF#refs/tags/}
            docker push ${{  secrets.ACR_LOGIN_SERVER_PROD }}/front:${GITHUB_REF#refs/tags/}
      
      - name: 'Retrive infomation'
        run: |
            echo ${GITHUB_REF#refs/tags/}
